### ISSUE TITLE
modern version

### ISSUE THREAD

**Issue by jimmywarting** [euank/node-parse-numeric-range#2]
```js
function parsePart (str) {
  // just a number
  if (/^-?\d+$/.test(str)) {
    return parseInt(str, 10)
  }

  var m
  
  // 1-5 or 1..5 (equivilant) or 1...5 (doesn't include 5)
  if ((m = str.match(/^(-?\d+)(-|\.\.\.?|\u2025|\u2026|\u22EF)(-?\d+)$/))) {
    var [_, lhs, sep, rhs] = m

    if (lhs && rhs) {
      lhs = parseInt(lhs)
      rhs = parseInt(rhs)
      var res = []
      var incr = lhs < rhs ? 1 : -1

      // Make it inclusive by moving the right 'stop-point' away by one.
      if (sep === '-' || sep === '..' || sep === '\u2025') rhs += incr

      for (var i = lhs; i !== rhs; i += incr) res.push(i)

      return res
    }
  }
  return []
}

/** 
 * @param {string} string  The string to parse
 * @returns {number[]}     Returns an energetic array.
 */
export default string => string.split(',').flatMap(parsePart)
```

(passes all existing tests)

**Comment by euank** [comment]
Do you want to make a pull-request with that improvement? Agreed that having flatMap built into js allows that bit to be expressed much more cleanly.

**Comment by jimmywarting** [comment]
What about all other features? Array destruction, es6 export, arrow fn?
Flatmap was added in node v11

Will definitely be breaking... Unless you target very new versions
How about having two versions of the file?

**Comment by euank** [comment]
It's published on npm. We can have a major version bump, and if someone needs the old version they can use the old package on npm, or they can go splunking through git history if they want the old copy of the file.

**Comment by jimmywarting** [comment]
thought about an alternative version that didin't use `flatMap` for wider targeted support and figured maybe this single function could work instead.

```js
/** 
 * @param {string} string  The string to parse
 * @returns {number[]}     Returns an energetic array.
 */
export default function parsePart (string) {
  let res = [], m
  for (let str of string.split(',')) {
    // just a number
    if (/^-?\d+$/.test(str)) {
      res.push(parseInt(str, 10))
    } else if ((m = str.match(/^(-?\d+)(-|\.\.\.?|\u2025|\u2026|\u22EF)(-?\d+)$/))) {
      // 1-5 or 1..5 (equivilant) or 1...5 (doesn't include 5)
      let [_, lhs, sep, rhs] = m

      if (lhs && rhs) {
        lhs = parseInt(lhs)
        rhs = parseInt(rhs)
        var incr = lhs < rhs ? 1 : -1

        // Make it inclusive by moving the right 'stop-point' away by one.
        if (sep === '-' || sep === '..' || sep === '\u2025') rhs += incr

        for (let i = lhs; i !== rhs; i += incr) res.push(i)
      }
    }
  }
  return res
}

```

probably faster than `flatMap` too?

**Comment by euank** [comment]
I'll ask again: do you want to make a pull-request to improve it?
If you're going to, it'll be easier to discuss it there.

I do think either of those are an improvement, though I'm not really sure about the performance implications of either.
I don't write as much js these days, so I'm inclined to trust you r judgement.

**Comment by jimmywarting** [comment]
tested it, second approach was 2x faster. making a PR
